modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/nexus-battle-mode/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="nexus:nexus_blue"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Nexus.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nexus-battle-mode"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod adds a "Nexus" block which allows you to play a team based tower defense game mode!'''



[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=false
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

