modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/nexus-battle-mode/issues"

[[mods]]
modId="nexus"
version="1.2.0"
displayName="Nexus"
itemIcon="nexus:nexus_blue"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Nexus.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nexus-battle-mode"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds a "Nexus" block which allows you to play a team based tower defense game mode!
 '''

[[dependencies.nexus]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nexus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"