modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/nexus-battle-mode/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="nexus:nexus_blue"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Nexus/refs/heads/master/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nexus-battle-mode"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod adds a "Nexus" block which allows you to play a team based tower defense game mode!'''

[modproperties.${mod_id}]
configuredBackground="nexus:textures/block/security_wall.png"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="magmacore"
    referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
    reason="Provides basic code and features such as update-checker"
    type="required"
    versionRange="${magmacore_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="multimine"
    mandatory=false
    type="optional"
    reason="Makes it possible to break a Nexus and other blocks with several people at the same time! Encourages team play!"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="patchouli"
    mandatory=false
    type="optional"
    reason="Is needed for the in-game description book, because the mod is quite complex."
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="guideme"
    mandatory=false
    type="optional"
    reason="Is needed for the in-game description book, because the mod is quite complex."
    versionRange="[21.5,)"
    ordering="NONE"
    side="BOTH"

